const MAIL_AND_PUSH_SECRETS = [
  "GMAIL_USER",
  "GMAIL_PASS",
  "WEB_APP_URL",
  "PUSH_VAPID_PUBLIC_KEY",
  "PUSH_VAPID_PRIVATE_KEY",
  "PUSH_VAPID_SUBJECT",
];

module.exports = {
  MAIL_AND_PUSH_SECRETS,
};
