const DOMAIN_EVENTS = {
  GROUP_USER_ADDED: "GROUP_USER_ADDED",
  GROUP_USER_REMOVED: "GROUP_USER_REMOVED",
  MATCH_CREATED: "MATCH_CREATED",
  MATCH_DELETED: "MATCH_DELETED",
  GROUP_ADMIN_ADDED: "GROUP_ADMIN_ADDED",
  TOURNAMENT_ADMIN_ADDED: "TOURNAMENT_ADMIN_ADDED",
  GROUP_ACCEPTED_INTO_TOURNAMENT: "GROUP_ACCEPTED_INTO_TOURNAMENT",
  TOURNAMENT_PLAYER_ADDED: "TOURNAMENT_PLAYER_ADDED",
  TOURNAMENT_PLAYER_REMOVED: "TOURNAMENT_PLAYER_REMOVED",
  TOURNAMENT_STARTED: "TOURNAMENT_STARTED",
  TOURNAMENT_FIXTURE_CONFIRMED: "TOURNAMENT_FIXTURE_CONFIRMED",
};

module.exports = { DOMAIN_EVENTS };
