const DOMAIN_EVENTS = {
  MATCH_CREATED: "MATCH_CREATED",
  MATCH_DELETED: "MATCH_DELETED",
  TOURNAMENT_ADMIN_ADDED: "TOURNAMENT_ADMIN_ADDED",
  GROUP_ACCEPTED_INTO_TOURNAMENT: "GROUP_ACCEPTED_INTO_TOURNAMENT",
  TOURNAMENT_PLAYER_ADDED: "TOURNAMENT_PLAYER_ADDED",
  TOURNAMENT_PLAYER_REMOVED: "TOURNAMENT_PLAYER_REMOVED",
  TOURNAMENT_STARTED: "TOURNAMENT_STARTED",
  TOURNAMENT_FIXTURE_CONFIRMED: "TOURNAMENT_FIXTURE_CONFIRMED",
  TOURNAMENT_CANCELLED: "TOURNAMENT_CANCELLED",
  MATCH_STARTER_REMOVED: "MATCH_STARTER_REMOVED",
};

module.exports = { DOMAIN_EVENTS };
