export type SeasonState = "abierta" | "cerrada";

export interface OwnSeason {
  id: string;
  groupId: string;
  nombre: string;
  estado: SeasonState;
  fechaInicio: string;
  createdAt: string;
  closedAt?: string;
}

export type SeasonErrorReason =
  | "UNAUTHENTICATED"
  | "ACCOUNT_REQUIRED"
  | "GROUP_NOT_FOUND"
  | "GROUP_INCOMPATIBLE"
  | "NOT_AUTHORIZED"
  | "SEASON_NOT_FOUND"
  | "VALIDATION_FAILED"
  | "OPEN_SEASON_ALREADY_EXISTS"
  | "SEASON_NOT_OPEN"
  | "SEASON_ALREADY_CLOSED"
  | "SEASON_GUARD_MISSING"
  | "SEASON_GUARD_INCOMPATIBLE"
  | "ACTIVE_MEMBERSHIPS_EXIST"
  | "MEMBERSHIP_SEASON_INCOMPATIBLE"
  | "MEMBERSHIP_PERIOD_INCOMPATIBLE"
  | "MEMBERSHIP_ACTIVE_GUARD_INCOMPATIBLE"
  | "APPROVAL_IN_PROGRESS"
  | "OWNERSHIP_CHANGED"
  | "INCOMPATIBLE_STATE"
  | "IDEMPOTENCY_CONFLICT"
  | "CONFLICT"
  | "DEPENDENCY_NOT_CONFIGURED"
  | "DEPENDENCY_UNAVAILABLE"
  | "INTERNAL_ERROR";
