"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { formatArs, getPaymentErrorMessage, getPaymentErrorReason, listMyObligations } from "@/services/paymentsService";
import type { Obligation } from "@/types/Payment";

export function MyObligationsView() {
  const [items, setItems] = useState<Obligation[]>([]); const [cursor, setCursor] = useState<string>(); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState(""); const feedback = useRef<HTMLDivElement>(null);
  const load = useCallback(async (append = false) => { setStatus("loading"); try { const page = await listMyObligations({ pageSize: 20, ...(append && cursor ? { cursor } : {}) }); setItems((current) => append ? [...current, ...page.items] : page.items); setCursor(page.nextCursor); setStatus("ready"); } catch (cause) { setError(getPaymentErrorMessage(getPaymentErrorReason(cause))); setStatus("error"); queueMicrotask(() => feedback.current?.focus()); } }, [cursor]);
  useEffect(() => { queueMicrotask(() => { void load(false); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  return <div ref={feedback} tabIndex={-1} aria-live="polite">{status === "loading" && items.length === 0 ? <p>Cargando obligaciones…</p> : null}{status === "error" ? <div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-5"><p>{error}</p><button onClick={() => void load(false)} className="mt-3 rounded-lg border px-4 py-2 font-semibold">Reintentar</button></div> : null}{status !== "error" && items.length === 0 ? <p className="rounded-xl border p-5 text-[var(--text-muted)]">No tenés obligaciones registradas.</p> : <ul className="divide-y rounded-xl border bg-[var(--surface)]">{items.map((item) => <li key={item.paymentId} className="p-4"><p className="mb-1 text-sm font-semibold text-[var(--text-muted)]">Grupo: {item.groupName}</p><div className="flex flex-wrap justify-between gap-2"><strong>{item.concept.name}</strong><span>{formatArs(item.amountMinor)}</span></div><p className="mt-1 text-sm text-[var(--text-muted)]">Vence {item.dueDate} · {item.periodKey ?? "Cobro específico"}</p><span className="mt-2 inline-flex rounded-full border px-2 py-1 text-xs font-semibold" aria-label="Estado económico: Pendiente de pago">Pendiente de pago</span>{item.overdue ? <p className="mt-1 text-sm font-semibold text-red-700">Vencida</p> : null}{item.exceptionReason ? <p className="mt-1 text-sm">Motivo de excepción: {item.exceptionReason}</p> : null}</li>)}</ul>}{cursor ? <button disabled={status === "loading"} onClick={() => void load(true)} className="mt-4 rounded-lg border px-4 py-2 font-semibold disabled:opacity-50">Cargar más</button> : null}</div>;
}
