"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { listActiveGroupMembersForOwnedGroup } from "@/services/membershipsService";
import {
  changeChargeConceptAmount, createChargeConcept, createChargeOccurrence, deactivateChargeConcept,
  formatArs, generateMembershipObligations, getPaymentErrorMessage, getPaymentErrorReason,
  listChargeConcepts, listChargeOccurrences, listGroupObligations, listMonthlyCandidates,
  newPaymentKey, parseArsMinor, renameChargeConcept,
} from "@/services/paymentsService";
import type { ActiveGroupMember } from "@/types/ActiveGroupMember";
import type { ChargeConcept, ChargeKind, ChargeOccurrence, GenerationRow, MonthlyMembershipCandidate, Obligation } from "@/types/Payment";

const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date());
const currentMonth = () => today().slice(0, 7);
const personName = (person: MonthlyMembershipCandidate["person"] | ActiveGroupMember["person"]) => person.status === "AVAILABLE" ? `${person.firstName} ${person.lastName}` : "Persona no disponible";
const conceptState = (value: ChargeConcept["estado"]) => value === "ACTIVE" ? "Activo" : "Inactivo";
const occurrenceState = (value: ChargeOccurrence["estado"]) => value === "UNUSED" ? "Disponible" : "Utilizado";
const eligibilityLabel = (value: MonthlyMembershipCandidate["eligibility"]) => ({ ELIGIBLE: "Elegible", NOT_OVERLAPPING: "Sin vigencia en el mes", UNPROVABLE: "Vigencia no comprobable" })[value];
const outcomeLabel = (value: GenerationRow["outcome"]) => ({ CREATED: "Creada", EXISTING: "Ya existente", FAILED: "No generada", PENDING_RECOVERY: "Pendiente de recuperación" })[value];
type OverrideDraft = { enabled: boolean; amount: string; reason: string };
type EditDialog = { kind: "name" | "amount"; concept: ChargeConcept; value: string };

export function OwnerEconomySection({ groupId, readOnly }: { groupId: string; readOnly: boolean }) {
  const [concepts, setConcepts] = useState<ChargeConcept[]>([]); const [obligations, setObligations] = useState<Obligation[]>([]);
  const [conceptCursor, setConceptCursor] = useState<string>(); const [obligationCursor, setObligationCursor] = useState<string>();
  const [selectedConceptId, setSelectedConceptId] = useState(""); const [expandedConceptId, setExpandedConceptId] = useState(""); const [showCreateConcept, setShowCreateConcept] = useState(false); const [name, setName] = useState(""); const [kind, setKind] = useState<ChargeKind>("MONTHLY"); const [amount, setAmount] = useState("");
  const [periodKey, setPeriodKey] = useState(currentMonth); const [dueDate, setDueDate] = useState(today); const [candidates, setCandidates] = useState<MonthlyMembershipCandidate[]>([]); const [activeMembers, setActiveMembers] = useState<ActiveGroupMember[]>([]); const [candidateCursor, setCandidateCursor] = useState<string | null>();
  const [occurrences, setOccurrences] = useState<ChargeOccurrence[]>([]); const [occurrenceToken, setOccurrenceToken] = useState(""); const [selectedOccurrence, setSelectedOccurrence] = useState(""); const [occurrenceName, setOccurrenceName] = useState("");
  const [selected, setSelected] = useState<string[]>([]); const [overrides, setOverrides] = useState<Record<string, OverrideDraft>>({}); const [rows, setRows] = useState<GenerationRow[]>([]); const [recoveryInput, setRecoveryInput] = useState<Record<string, unknown> | null>(null); const [editDialog, setEditDialog] = useState<EditDialog | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const liveRef = useRef<HTMLDivElement>(null); const busyRef = useRef(false);
  const selectedConcept = concepts.find((item) => item.conceptId === selectedConceptId);

  const report = (cause: unknown) => { setError(getPaymentErrorMessage(getPaymentErrorReason(cause))); queueMicrotask(() => liveRef.current?.focus()); };
  const loadBase = useCallback(async () => { setError(""); try { const [conceptPage, obligationPage] = await Promise.all([listChargeConcepts({ groupId, pageSize: 50 }), listGroupObligations({ groupId, pageSize: 20 })]); setConcepts(conceptPage.items); setConceptCursor(conceptPage.nextCursor); setObligations(obligationPage.items); setObligationCursor(obligationPage.nextCursor); } catch (cause) { report(cause); } }, [groupId]);
  useEffect(() => { void loadBase(); }, [loadBase]);

  const mutate = async (operation: () => Promise<unknown>, success: string) => { if (busyRef.current) return false; busyRef.current = true; setBusy(true); setError(""); try { await operation(); setNotice(success); await loadBase(); return true; } catch (cause) { report(cause); return false; } finally { busyRef.current = false; setBusy(false); } };
  const createConceptSubmit = async (event: React.FormEvent) => { event.preventDefault(); const minor = parseArsMinor(amount); if (minor === null) return setError("Ingresá un importe ARS positivo con hasta dos decimales."); const created = await mutate(() => createChargeConcept({ groupId, name, kind, defaultAmountMinor: minor, idempotencyKey: newPaymentKey() }), "Concepto creado."); if (created) { setName(""); setAmount(""); setKind("MONTHLY"); setShowCreateConcept(false); } };
  const submitEdit = async (event: React.FormEvent) => { event.preventDefault(); if (!editDialog) return; const value = editDialog.value.trim(); if (editDialog.kind === "name" && !value) return setError("Ingresá un nombre para el concepto."); const minor = editDialog.kind === "amount" ? parseArsMinor(value) : null; if (editDialog.kind === "amount" && minor === null) return setError("El importe no es válido."); const applied = await mutate(() => editDialog.kind === "name" ? renameChargeConcept({ groupId, conceptId: editDialog.concept.conceptId, name: value, expectedVersion: editDialog.concept.version, idempotencyKey: newPaymentKey() }) : changeChargeConceptAmount({ groupId, conceptId: editDialog.concept.conceptId, defaultAmountMinor: minor!, expectedVersion: editDialog.concept.version, idempotencyKey: newPaymentKey() }), editDialog.kind === "name" ? "Concepto renombrado." : "Importe general actualizado."); if (applied) setEditDialog(null); };
  const clearGenerationContext = () => { setSelected([]); setOverrides({}); setRows([]); setRecoveryInput(null); setNotice(""); setError(""); };

  const loadOccurrences = useCallback(async (concept: ChargeConcept) => { try { const page = await listChargeOccurrences({ groupId, conceptId: concept.conceptId, pageSize: 50 }); setOccurrences(page.items); setOccurrenceToken(page.occurrenceListToken); setSelectedOccurrence(page.items[0]?.occurrenceKey ?? ""); } catch (cause) { report(cause); } }, [groupId]);
  const chooseConcept = async (id: string) => { if (readOnly || (busyRef.current && expandedConceptId !== id)) return; if (expandedConceptId === id) { setExpandedConceptId(""); return; } setExpandedConceptId(id); if (selectedConceptId === id) return; setSelectedConceptId(id); clearGenerationContext(); setCandidates([]); setOccurrences([]); setSelectedOccurrence(""); setActiveMembers([]); const concept = concepts.find((item) => item.conceptId === id); if (!concept) return; if (concept.kind === "ONE_TIME") { await loadOccurrences(concept); try { const page = await listActiveGroupMembersForOwnedGroup({ groupId, pageSize: 20 }); setActiveMembers(page.items); setCandidateCursor(page.nextCursor); } catch (cause) { report(cause); } } };
  const loadCandidates = async (append = false) => { try { const page = await listMonthlyCandidates({ groupId, periodKey, pageSize: 20, ...(append && candidateCursor ? { cursor: candidateCursor } : {}) }); setCandidates((current) => append ? [...current, ...page.items] : page.items); setCandidateCursor(page.nextCursor ?? null); if (!append) clearGenerationContext(); } catch (cause) { report(cause); } };
  const loadMoreActive = async () => { if (!candidateCursor) return; try { const page = await listActiveGroupMembersForOwnedGroup({ groupId, pageSize: 20, cursor: candidateCursor }); setActiveMembers((current) => [...current, ...page.items]); setCandidateCursor(page.nextCursor); } catch (cause) { report(cause); } };
  const createOccurrenceSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedConcept || !occurrenceToken) return; await mutate(async () => { await createChargeOccurrence({ groupId, conceptId: selectedConcept.conceptId, expectedConceptVersion: selectedConcept.version, name: occurrenceName, occurrenceListToken: occurrenceToken, idempotencyKey: newPaymentKey() }); await loadOccurrences(selectedConcept); setOccurrenceName(""); }, "Ocurrencia creada y disponible."); };
  const toggle = (membershipId: string) => { setSelected((current) => current.includes(membershipId) ? current.filter((id) => id !== membershipId) : [...current, membershipId]); setOverrides((current) => { const next = { ...current }; delete next[membershipId]; return next; }); setRows([]); setRecoveryInput(null); };
  const generate = async (fixed?: Record<string, unknown>) => { if (!selectedConcept || busyRef.current) return; const exceptions: Array<{ membershipId: string; amountMinor: number; reason: string }> = []; for (const membershipId of selected) { const item = overrides[membershipId]; if (!item?.enabled) continue; const parsed = parseArsMinor(item.amount); if (parsed === null || !item.reason.trim()) return setError("Cada excepción necesita importe válido y motivo."); if (parsed === selectedConcept.defaultAmountMinor) return setError("El otro importe debe ser distinto del importe general; desactivá “Usar otro importe” si no necesitás una excepción."); exceptions.push({ membershipId, amountMinor: parsed, reason: item.reason }); } const input = fixed ?? { groupId, conceptId: selectedConcept.conceptId, expectedConceptVersion: selectedConcept.version, membershipIds: selected, dueDate, baseAmountMinor: selectedConcept.defaultAmountMinor, exceptions, generationIdempotencyKey: newPaymentKey(), kind: selectedConcept.kind, ...(selectedConcept.kind === "MONTHLY" ? { periodKey } : { occurrenceKey: selectedOccurrence }) }; busyRef.current = true; setBusy(true); setError(""); try { const result = await generateMembershipObligations(input); setRows(result.rows); setRecoveryInput(result.complete ? null : input); setNotice(result.complete ? "Generación finalizada por fila." : "Hay resultados pendientes de recuperación. Reintentá la misma intención."); const page = await listGroupObligations({ groupId, pageSize: 20 }); setObligations(page.items); setObligationCursor(page.nextCursor); } catch (cause) { report(cause); } finally { busyRef.current = false; setBusy(false); } };
  const generationMembers = selectedConcept?.kind === "MONTHLY" ? candidates.map((item) => ({ id: item.membershipId, label: personName(item.person), detail: `${item.membershipState === "ACTIVE" ? "Activa" : "Finalizada"} · ${eligibilityLabel(item.eligibility)}`, eligible: item.eligibility === "ELIGIBLE" })) : activeMembers.map((item) => ({ id: item.membershipId, label: personName(item.person), detail: "Activa", eligible: true }));
  const selectedAreValid = selected.length > 0 && selected.every((id) => generationMembers.some((item) => item.id === id && item.eligible));
  const exceptionsAreValid = selected.every((id) => { const draft = overrides[id]; if (!draft?.enabled) return true; const parsed = parseArsMinor(draft.amount); return parsed !== null && parsed !== selectedConcept?.defaultAmountMinor && Boolean(draft.reason.trim()); });
  const canGenerate = Boolean(selectedConcept && /^\d{4}-\d{2}-\d{2}$/.test(dueDate) && selectedAreValid && exceptionsAreValid && (selectedConcept.kind === "MONTHLY" ? /^\d{4}-(0[1-9]|1[0-2])$/.test(periodKey) : Boolean(selectedOccurrence)));
  const editValid = Boolean(editDialog && (editDialog.kind === "name" ? editDialog.value.trim() : parseArsMinor(editDialog.value) !== null));

  return <section className="lg:col-span-2 space-y-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7">
    <div ref={liveRef} tabIndex={-1} aria-live="polite"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Economía</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Obligaciones por Membresía · ARS · fechas de Buenos Aires.</p></div>{!readOnly ? <button type="button" disabled={busy} aria-expanded={showCreateConcept} aria-controls="create-charge-concept-form" onClick={() => setShowCreateConcept((visible) => !visible)} className="w-full rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50 sm:w-auto">{showCreateConcept ? "Ocultar formulario" : "Crear concepto"}</button> : null}</div>{notice ? <p className="mt-2 text-sm text-emerald-700">{notice}</p> : null}{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}</div>
    {!readOnly && showCreateConcept ? <form id="create-charge-concept-form" onSubmit={createConceptSubmit} className="grid gap-3 rounded-xl border border-[var(--border)] p-4 sm:grid-cols-4"><label className="text-sm">Nombre<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Tipo<select value={kind} onChange={(e) => setKind(e.target.value as ChargeKind)} className="mt-1 w-full rounded-lg border p-2"><option value="MONTHLY">Mensual</option><option value="ONE_TIME">Cobro único</option></select></label><label className="text-sm">Importe ARS<input required inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><button disabled={busy} className="self-end rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy ? "Guardando…" : "Guardar"}</button></form> : null}
    <div><h3 className="font-semibold">Conceptos</h3>{concepts.length === 0 ? <p className="mt-2 text-sm text-[var(--text-muted)]">No hay conceptos.</p> : <div className="mt-2 grid gap-2">{concepts.map((concept) => <article key={concept.conceptId} className={`rounded-xl border p-3 ${expandedConceptId === concept.conceptId ? "border-orange-500" : "border-[var(--border)]"}`}><div className="flex flex-wrap items-center justify-between gap-2">{readOnly || concept.estado !== "ACTIVE" ? <div><span className="font-semibold">{concept.name}</span><span className="ml-2 text-xs text-[var(--text-muted)]">{concept.kind === "MONTHLY" ? "Mensual" : "Cobro único"} · v{concept.version} · {formatArs(concept.defaultAmountMinor)}</span></div> : <button type="button" aria-expanded={expandedConceptId === concept.conceptId} aria-controls={`economy-concept-generation-${concept.conceptId}`} onClick={() => void chooseConcept(concept.conceptId)} className="text-left"><span className="font-semibold">{concept.name}</span><span className="ml-2 text-xs text-[var(--text-muted)]">{concept.kind === "MONTHLY" ? "Mensual" : "Cobro único"} · v{concept.version} · {formatArs(concept.defaultAmountMinor)}</span></button>}<span className="inline-flex rounded-full border px-2 py-1 text-xs font-semibold" aria-label={`Estado del concepto: ${conceptState(concept.estado)}`}>{conceptState(concept.estado)}</span>{!readOnly && expandedConceptId === concept.conceptId && concept.estado === "ACTIVE" ? <div className="flex gap-2 text-sm"><button type="button" onClick={() => setEditDialog({ kind: "name", concept, value: concept.name })} className="underline">Renombrar</button><button type="button" onClick={() => setEditDialog({ kind: "amount", concept, value: (concept.defaultAmountMinor / 100).toFixed(2) })} className="underline">Importe</button><button type="button" onClick={() => void mutate(() => deactivateChargeConcept({ groupId, conceptId: concept.conceptId, expectedVersion: concept.version, idempotencyKey: newPaymentKey() }), "Concepto desactivado; la historia se conserva.")} className="text-red-700 underline">Desactivar</button></div> : null}</div></article>)}</div>}{conceptCursor ? <button className="mt-2 text-sm underline" onClick={async () => { const page = await listChargeConcepts({ groupId, pageSize: 50, cursor: conceptCursor }); setConcepts((items) => [...items, ...page.items]); setConceptCursor(page.nextCursor); }}>Cargar más conceptos</button> : null}</div>
    {!readOnly && expandedConceptId === selectedConceptId && selectedConcept?.estado === "ACTIVE" ? <div id={`economy-concept-generation-${selectedConcept.conceptId}`} className="space-y-4 rounded-xl border border-orange-200 bg-orange-50/30 p-4"><h3 className="font-semibold">Generar obligaciones · {selectedConcept.name}</h3>{selectedConcept.kind === "MONTHLY" ? <div className="flex flex-wrap items-end gap-3"><label className="text-sm">Mes<input type="month" max={currentMonth()} value={periodKey} onChange={(e) => { setPeriodKey(e.target.value); setCandidates([]); clearGenerationContext(); }} className="mt-1 block rounded-lg border p-2" /></label><button type="button" onClick={() => void loadCandidates(false)} className="rounded-lg border border-orange-500 px-4 py-2 font-semibold">Listar activas y finalizadas</button></div> : <div><h4 className="text-sm font-semibold">Cobro específico</h4><p className="mt-1 text-sm text-[var(--text-muted)]">Identifica un cobro único reutilizable, por ejemplo “Camiseta 2026”. Primero se consulta la lista existente para evitar duplicar la misma identidad.</p>{occurrences.length ? <select aria-label="Cobro específico" value={selectedOccurrence} onChange={(e) => { setSelectedOccurrence(e.target.value); clearGenerationContext(); }} className="mt-2 rounded-lg border p-2">{occurrences.map((item) => <option key={item.occurrenceKey} value={item.occurrenceKey}>{item.name} · {occurrenceState(item.estado)}</option>)}</select> : <p className="mt-2 text-sm text-[var(--text-muted)]">Lista consultada: todavía no hay cobros específicos.</p>}<form onSubmit={createOccurrenceSubmit} className="mt-3 flex flex-wrap gap-2"><input required aria-label="Nombre del nuevo cobro específico" value={occurrenceName} onChange={(e) => setOccurrenceName(e.target.value)} className="rounded-lg border p-2" placeholder="Ej.: Camiseta 2026" /><button disabled={!occurrenceToken || busy} className="rounded-lg border border-orange-500 px-4 py-2 font-semibold">Crear cobro específico</button></form></div>}
      {generationMembers.length ? <div className="space-y-2"><h4 className="text-sm font-semibold">Membresías</h4>{generationMembers.map((item) => { const isSelected = selected.includes(item.id); const draft = overrides[item.id]; const equalGeneral = draft?.enabled && parseArsMinor(draft.amount) === selectedConcept.defaultAmountMinor; return <div key={item.id} className="rounded-lg border bg-white p-3 text-sm"><label className="block"><input type="checkbox" checked={isSelected} disabled={!item.eligible} onChange={() => toggle(item.id)} className="mr-2" /><span className="font-semibold">{item.label}</span> · {item.detail}</label>{isSelected ? <div className="mt-2 space-y-2 border-l-2 border-orange-200 pl-3"><p>Importe general: <strong>{formatArs(selectedConcept.defaultAmountMinor)}</strong></p><label className="inline-flex items-center gap-2"><input type="checkbox" checked={draft?.enabled ?? false} onChange={(e) => setOverrides((all) => ({ ...all, [item.id]: { enabled: e.target.checked, amount: "", reason: "" } }))} />Usar otro importe</label>{draft?.enabled ? <div className="grid gap-2 sm:grid-cols-2"><label>Importe alternativo ARS<input aria-label={`Importe alternativo para ${item.label}`} value={draft.amount} onChange={(e) => setOverrides((all) => ({ ...all, [item.id]: { ...all[item.id], amount: e.target.value } }))} className="mt-1 w-full rounded border p-2" /></label><label>Motivo obligatorio<input aria-label={`Motivo de excepción para ${item.label}`} value={draft.reason} onChange={(e) => setOverrides((all) => ({ ...all, [item.id]: { ...all[item.id], reason: e.target.value } }))} className="mt-1 w-full rounded border p-2" /></label>{equalGeneral ? <p role="alert" className="sm:col-span-2 text-amber-800">El importe alternativo coincide con el general. Desactivá “Usar otro importe” o ingresá un valor diferente.</p> : null}</div> : null}</div> : null}</div>; })}{candidateCursor ? <button type="button" onClick={() => void (selectedConcept.kind === "MONTHLY" ? loadCandidates(true) : loadMoreActive())} className="text-sm underline">Cargar más Membresías</button> : null}</div> : null}
      <div className="flex flex-wrap items-end gap-3"><label className="text-sm">Vencimiento<input type="date" value={dueDate} onChange={(e) => { setDueDate(e.target.value); setRows([]); setRecoveryInput(null); }} className="mt-1 block rounded-lg border p-2" /></label><p className="text-sm">Importe general confirmado: <strong>{formatArs(selectedConcept.defaultAmountMinor)}</strong></p><button type="button" disabled={busy || !canGenerate} onClick={() => void generate()} className="rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Confirmar generación</button>{recoveryInput ? <button type="button" disabled={busy} onClick={() => void generate(recoveryInput)} className="rounded-lg border border-amber-600 px-4 py-2 font-semibold">Recuperar misma intención</button> : null}</div>
      {rows.length ? <div aria-live="polite" className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Integrante</th><th className="p-2">Resultado de generación</th><th className="p-2">Detalle</th></tr></thead><tbody>{rows.map((row) => <tr key={row.membershipId} className="border-t"><td className="p-2">{generationMembers.find((item) => item.id === row.membershipId)?.label ?? "Persona no disponible"}</td><td className="p-2"><span className="inline-flex rounded-full border px-2 py-1 font-semibold">{outcomeLabel(row.outcome)}</span></td><td className="p-2">{row.errorCode ? getPaymentErrorMessage(row.errorCode as Parameters<typeof getPaymentErrorMessage>[0]) : row.payment ? formatArs(row.payment.amountMinor) : "Requiere recuperación técnica"}</td></tr>)}</tbody></table></div> : null}</div> : null}
    <div><h3 className="font-semibold">Obligaciones del Grupo</h3>{obligations.length === 0 ? <p className="mt-2 text-sm text-[var(--text-muted)]">No hay obligaciones.</p> : <ul className="mt-2 divide-y rounded-xl border">{obligations.map((item) => <li key={item.paymentId} className="p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><strong>{item.person?.status === "AVAILABLE" ? `${item.person.firstName} ${item.person.lastName}` : "Persona no disponible"}</strong><span className="inline-flex rounded-full border px-2 py-1 text-xs font-semibold" aria-label="Estado económico: Pendiente de pago">Pendiente de pago</span></div><p className="mt-1">{item.concept.name} · {formatArs(item.amountMinor)} · vence {item.dueDate} · {item.periodKey ?? "Cobro específico"}</p>{item.overdue ? <span className="mt-1 inline-flex rounded-full border border-red-300 px-2 py-1 font-semibold text-red-800">Vencida</span> : null}{item.exceptionReason ? <p className="text-[var(--text-muted)]">Excepción: {item.exceptionReason}</p> : null}</li>)}</ul>}{obligationCursor ? <button className="mt-2 text-sm underline" onClick={async () => { const page = await listGroupObligations({ groupId, pageSize: 20, cursor: obligationCursor }); setObligations((items) => [...items, ...page.items]); setObligationCursor(page.nextCursor); }}>Cargar más obligaciones</button> : null}</div>
    {editDialog ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="presentation" onKeyDown={(event) => { if (event.key === "Escape" && !busy) setEditDialog(null); }}><form role="dialog" aria-modal="true" aria-labelledby="concept-edit-title" onSubmit={submitEdit} className="w-full max-w-md rounded-2xl bg-[var(--surface)] p-6 shadow-xl"><h3 id="concept-edit-title" className="text-lg font-semibold">{editDialog.kind === "name" ? "Editar nombre" : "Editar importe general"}</h3><p className="mt-1 text-sm text-[var(--text-muted)]">{editDialog.concept.name} · versión {editDialog.concept.version}</p><label className="mt-4 block text-sm">{editDialog.kind === "name" ? "Nuevo nombre" : "Nuevo importe ARS"}<input autoFocus required inputMode={editDialog.kind === "amount" ? "decimal" : undefined} value={editDialog.value} onChange={(event) => setEditDialog({ ...editDialog, value: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><div className="mt-5 flex justify-end gap-3"><button type="button" disabled={busy} onClick={() => setEditDialog(null)} className="rounded-lg border px-4 py-2 font-semibold disabled:opacity-50">Cancelar</button><button type="submit" disabled={busy || !editValid} className="rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy ? "Guardando…" : "Confirmar"}</button></div></form></div> : null}
  </section>;
}
