"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { formatArs, getPaymentErrorMessage, getPaymentErrorReason, listChargeConcepts, listChargeOccurrences, listGroupObligations } from "@/services/paymentsService";
import type { ChargeConcept, ChargeOccurrence, Obligation } from "@/types/Payment";

export function TreasuryEconomyView({ groupId, onAccessLost }: { groupId: string; onAccessLost: () => void }) {
  const [concepts, setConcepts] = useState<ChargeConcept[]>([]); const [obligations, setObligations] = useState<Obligation[]>([]); const [occurrences, setOccurrences] = useState<Record<string, ChargeOccurrence[]>>({});
  const [conceptCursor, setConceptCursor] = useState<string>(); const [obligationCursor, setObligationCursor] = useState<string>(); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState(""); const inFlight = useRef(false);
  const fail = useCallback((cause: unknown) => { const reason = getPaymentErrorReason(cause); setConcepts([]); setObligations([]); setOccurrences({}); setConceptCursor(undefined); setObligationCursor(undefined); if (["GROUP_TREASURY_NOT_AUTHORIZED", "GROUP_NOT_ACCESSIBLE", "GROUP_NOT_OPERATIONAL"].includes(reason)) { onAccessLost(); return; } setError(getPaymentErrorMessage(reason)); setStatus("error"); }, [onAccessLost]);
  const load = useCallback(async () => { if (inFlight.current) return; inFlight.current = true; setStatus("loading"); setError(""); try { const [conceptPage, obligationPage] = await Promise.all([listChargeConcepts({ groupId, pageSize: 50 }), listGroupObligations({ groupId, pageSize: 20 })]); setConcepts(conceptPage.items); setConceptCursor(conceptPage.nextCursor); setObligations(obligationPage.items); setObligationCursor(obligationPage.nextCursor); setStatus("ready"); } catch (cause) { fail(cause); } finally { inFlight.current = false; } }, [fail, groupId]);
  useEffect(() => { void load(); return () => { inFlight.current = false; }; }, [load]);
  async function showOccurrences(concept: ChargeConcept) { try { const page = await listChargeOccurrences({ groupId, conceptId: concept.conceptId, pageSize: 50 }); setOccurrences((current) => ({ ...current, [concept.conceptId]: page.items })); } catch (cause) { fail(cause); } }
  async function moreConcepts() { if (!conceptCursor) return; try { const page = await listChargeConcepts({ groupId, pageSize: 50, cursor: conceptCursor }); setConcepts((items) => [...items, ...page.items]); setConceptCursor(page.nextCursor); } catch (cause) { fail(cause); } }
  async function moreObligations() { if (!obligationCursor) return; try { const page = await listGroupObligations({ groupId, pageSize: 20, cursor: obligationCursor }); setObligations((items) => [...items, ...page.items]); setObligationCursor(page.nextCursor); } catch (cause) { fail(cause); } }
  return <section aria-labelledby="treasury-economy-title" className="space-y-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><div><h2 id="treasury-economy-title" className="text-xl font-semibold">Economía · sólo consulta</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Conceptos, cobros específicos y obligaciones del Grupo. No hay operaciones de escritura disponibles.</p></div>{status === "loading" ? <p role="status">Cargando economía…</p> : null}{status === "error" ? <div role="alert"><p className="text-red-700">{error}</p><button type="button" className="mt-3 min-h-11 rounded-lg border px-4 py-2 font-semibold" onClick={() => void load()}>Reintentar</button></div> : null}{status === "ready" ? <><div><h3 className="font-semibold">Conceptos y cobros específicos</h3>{concepts.length ? <ul className="mt-2 grid gap-3">{concepts.map((concept) => <li key={concept.conceptId} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p><strong>{concept.name}</strong> · {formatArs(concept.defaultAmountMinor)} · {concept.kind === "MONTHLY" ? "Mensual" : "Cobro único"}</p><button type="button" className="min-h-11 rounded-lg border px-4 py-2 font-semibold" onClick={() => void showOccurrences(concept)}>Ver cobros específicos</button></div>{occurrences[concept.conceptId] ? occurrences[concept.conceptId].length ? <ul className="mt-3 list-disc pl-6 text-sm">{occurrences[concept.conceptId].map((item) => <li key={item.occurrenceKey}>{item.name} · {item.estado === "UNUSED" ? "Disponible" : "Utilizada"}</li>)}</ul> : <p className="mt-3 text-sm text-[var(--text-muted)]">No hay cobros específicos para este concepto.</p> : null}</li>)}</ul> : <p className="mt-2 text-sm text-[var(--text-muted)]">No hay conceptos.</p>}{conceptCursor ? <button type="button" className="mt-3 min-h-11 underline" onClick={() => void moreConcepts()}>Cargar más conceptos</button> : null}</div><div><h3 className="font-semibold">Obligaciones del Grupo</h3>{obligations.length ? <ul className="mt-2 divide-y rounded-xl border">{obligations.map((item) => <li key={item.paymentId} className="p-3 text-sm"><strong>{item.person?.status === "AVAILABLE" ? `${item.person.firstName} ${item.person.lastName}` : "Persona no disponible"}</strong><p>{item.concept.name} · {formatArs(item.amountMinor)} · vence {item.dueDate}</p></li>)}</ul> : <p className="mt-2 text-sm text-[var(--text-muted)]">No hay obligaciones.</p>}{obligationCursor ? <button type="button" className="mt-3 min-h-11 underline" onClick={() => void moreObligations()}>Cargar más obligaciones</button> : null}</div></> : null}</section>;
}
